Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TaskTrackerPrototype.Controllers
{
    public class LoginController : Controller
    {
        // GET: /Login/
        public IActionResult Index()
        {
            return View();
        }
        //hash input password
        //use username as key to check against stored password hash
    }
}

Controllers/SignupController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TaskTrackerPrototype.Controllers
{
    public class SignupController : Controller
    {
        // GET: /Signup/
        public IActionResult Index()
        {
            return View();
        }
        //hash password and store to database
    }
}

Views/Login/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link rel="stylesheet" type="text/css" href="~/css/StyleSheet.css" />
<div class="login">
    <h1>Login to PLANR</h1>
    <form method="post" action="">
        <p>Enter your username or email:</p>
        <p><input type="text" name="login" value="" placeholder="Username or Email"></p>
        <p>Enter your password:</p>
        <p><input type="password" name="password" value="" placeholder="Password"></p>

        <p class="remember_me">
            <label>
                <input type="checkbox" name="remember_me" id="remember_me">
                Remember me on this computer
            </label>
        </p>
        <p class="remember_me">
            <label>
                Don't have an account? <a asp-area="" asp-controller="Signup" asp-action="Index">Sign up here.</a>
            </label>
        </p>
        <p class="submit"><input type="submit" name="commit" value="Login"></p>
    </form>
</div>

<div class="login-help">
    <p style="color: #555555;">Forgot your password? <a href="#" style="color: #4475A0;">Click here to reset it</a>.</p>
</div>


